### ISSUE TITLE
Not working in iOS 9.1 beta.

### ISSUE THREAD

**Issue by Shebuka** [ddeville/LLBSDMessaging#3]
All is working flawlessly in iOS 8, but in iOS 9 it simply not working...
The Server app seems to start fine (no error log), but when I try to send a message with Client app on timer fire (each 5 seconds) I get an error in device console:

```
kernel[0] <Notice>: Sandbox: testApp(1033) deny(1) sysctl-read kern.proc.all
```

Sometimes I get a SIGPIPE exception with this call stack:

```
#0  0x393cbfbc in mach_msg_trap ()
#1  0x393cbdbc in mach_msg ()
#2  0x26ba74ac in __CFRunLoopServiceMachPort ()
#3  0x26ba5832 in __CFRunLoopRun ()
#4  0x26af8128 in CFRunLoopRunSpecific ()
#5  0x26af7f1c in CFRunLoopRunInMode ()
#6  0x2ff49af8 in GSEventRunModal ()
#7  0x2af809bc in UIApplicationMain ()
#8  0x000d83ec in main at /path/to/project/testApp/main.m:25
```

and when I click on "Continue program execution" one or two of following errors:

```
2015-09-17 13:49:24.948 [thread=8991 ] DEBUG    AppDelegate::checkinWithServerActive IPCClient sendMessage: The operation couldn’t be completed. Broken pipe
2015-09-17 13:49:24.954 [thread=23687] DEBUG    AppDelegate::checkinWithServerActive IPCClient sendMessage: The operation couldn’t be completed. Operation canceled
2015-09-17 13:55:45.129 [thread=15879] DEBUG    AppDelegate::checkinWithServerActive IPCClient sendMessage: The operation couldn’t be completed. (com.ddeville.llbsdmessaging error -102.)
```

Is this not supported anymore in iOS 9 or can you help solve this?

**Comment by tiagoaap** [comment]
Hi @Shebuka ,
I think that I've the same problem with iOS 9.
Did you figure it out what is the problem here?

**Comment by Shebuka** [comment]
@tiagoaap nope, after hours of debugging and in need of rapid solution I've moved to a UDP IPC.

**Comment by Alex-Ozun** [comment]
@Shebuka Hey there! Could you please give me some details on UDP IPC approach that you mantioned here? Did you use some library for this? Thanks in advance!

**Comment by Shebuka** [comment]
@Alex-Ozun I'm using IPC only for signaling and for my needs i've found this really good written IPC over UDP library called [MeshPipe](https://github.com/nevyn/MeshPipe). Please be aware of "[some hard-wired limitations](https://github.com/nevyn/MeshPipe#meshpipe)".

**Comment by Alex-Ozun** [comment]
@Shebuka Thanks, man! I was looking at this lib some time before. You convinced me to try it out.
